### ISSUE TITLE
Maximum category number per row

### ISSUE THREAD

**Issue by denis631** [drewdotpro/nodebb-theme-persona-blocks#1]
I know it is not really an issue and maybe it is nor really related to your plugin in generall, but I hope you can help me. 

The problem is, that I can not show more, than 4 categories on the same line.
![bildschirmfoto 2015-09-24 um 09 45 07](https://cloud.githubusercontent.com/assets/6100421/10067975/fd8decfc-62a0-11e5-97fc-a2d4fa6aae23.png)

On bigger screens there is enough place for it. I though, that it is a constant, so I've search the files, for number 4 (maximum number of categories per row), but unfortunately didn't find anything.

With content it looks like this.
![bildschirmfoto 2015-09-24 um 09 42 14](https://cloud.githubusercontent.com/assets/6100421/10067995/2b4bb8ae-62a1-11e5-8ab5-4f208aedf82f.png)

P.S. I'm not an frontend-backend developer. I have nothing to do with web, but I've got this task, which should be done.

**Comment by drewdotpro** [comment]
This is a Masonry thing. That side area is for the side bar. This theme doesn't change the layout like that.

You'd be best raising it on the [Community Forum](https://community.nodebb.org/).

Probably you're looking to change the category "custom class" (see the control panel)
Setting it to:
col-lg-2 col-md-4 col-xs-6

Would see 6 on large displays, 3 on medium and 2 on small (the whole area is col-12 wide)

**Comment by drewdotpro** [comment]
Updated reply. Use the forum for any more support. Thanks.
